### ISSUE TITLE
请问有在中文数据上预训练过的模型吗？

### ISSUE THREAD

**Issue by sherlcok314159** [thunlp/ERICA#1]

**Comment by HuimengZhang** [comment]
同问

**Comment by thuqinyj16** [comment]
您好，暂时没有训练。后续我们会进一步推出中文版的ERICA模型，您也可以对代码进行少量修改，以适配中文模型的训练。若对于代码修改有疑问，烦请联系我 (yujiaqin16@gmail.com) ，感谢！
