### ISSUE TITLE
Missing the setup.py file in transformers package.

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [thunlp/ERICA#3]

**Comment by zhaowei-wang-nlp** [comment]
README.md says that we need to use 'pip install .' to intsall transformers. However but I can't use this command in the '/pretrain/code/pretrain/transformers/' folder.

**Comment by thuqinyj16** [comment]
Thx for pointing it out, we use the version of 2.5.0, plz install by ``pip install transformers==2.5.0'', note we modify some code in the transformers folder.
